### ISSUE TITLE
members with administrator privileges can change the status of other members to suspended or reset it to active or inactive --2 pointss

### ISSUE THREAD

**Issue by amnivir** [layheng/pog#14]

**Comment by amnivir** [comment]
update another coloum for member status.

**Comment by amnivir** [comment]
This one needs to be implemented to get more points...

**Comment by amnivir** [comment]
2points

**Comment by layheng** [comment]
Admin can change status of members through admin->manage Members page. Done.

**Comment by layheng** [comment]
Admin can change status of members through admin->manage Members page. Done.
