### ISSUE TITLE
Post content  7 points

### ISSUE THREAD

**Issue by amnivir** [layheng/pog#20]
Privilege change on posts
change public posts.
change permission to contents

**Comment by xdwang0726** [comment]
admin/ owner privilege update, delete the post

**Comment by xdwang0726** [comment]
Privilege change on posts => update delete the posts
change permission to contents =>view only or view and comment, permission = 0

**Comment by layheng** [comment]
"change public posts" is done.

**Comment by amnivir** [comment]
Privilege change on posts => update delete the posts -> done
change permission to contents =>view only or view and comment, permission = 0 --> done
At the moment any one can comment , but if persmission is set to 1 then other members cannot edit & delete the post, true otherwise
