### ISSUE TITLE
Report of groups or members by specific category such as interest, age, profession, region, etc --- 2 points

### ISSUE THREAD

**Issue by amnivir** [layheng/pog#6]

**Comment by amnivir** [comment]
This one was not implemented due to time limitation.
We can generate reports based on interest, age & region
This can fetch 2 more points

**Comment by JayaGaut** [comment]
I am working on this

**Comment by xdwang0726** [comment]
it's done, right? can we close this? @JayaGaut

**Comment by JayaGaut** [comment]
I guess waiting for shivam he wanted to add some other things
