### ISSUE TITLE
Status of a member 

### ISSUE THREAD

**Issue by amnivir** [layheng/pog#9]
Status of a member can be either active, inactive or suspended. 

An active member can have access to all the functionalities of a member. 

An inactive member will not be visible to other members; nor would communication be sent to an inactive member. 

A suspended member will not be able to lo-gin to the POWON system until his/her status is changed.

**Comment by amnivir** [comment]
A suspended member will not be able to lo-gin to the POWON system until his/her status is changed.-->this is done.

@layheng can you implement this -->An inactive member will not be visible to other members; nor would communication be sent to an inactive member.

**Comment by amnivir** [comment]
still needs to be done... @layheng ?

**Comment by JayaGaut** [comment]
@layheng are you working on this?

**Comment by layheng** [comment]
@JayaGaut : I work on public info (adding update page) first. You can work on the member status if you can.

**Comment by JayaGaut** [comment]
Cool Thanks

**Comment by JayaGaut** [comment]
@layheng I have completed the inactive member part. I would suggest that you do admin who make profile suspend as I did some changes and admin thing stopped working. Let me know what you think.

**Comment by layheng** [comment]
Admin can change status of members through admin->manage Members page. Done.
